### ISSUE TITLE
Resubmit to CRAN

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/Wats#8]
Email July 2:
>These Suggests: BayesSingleSub and Suggests: simPop respectively but do not use those packages conditionally as required by 'Writing R Extensions'.
>
>Both of the dependencies have been archived and so your packages now fail their checks.  Please correct ASAP and before Jul 16 to safely retain the packages on CRAN.
>
>-- 
>Brian D. Ripley,                  ripley@stats.ox.ac.uk
>Emeritus Professor of Applied Statistics, University of Oxford

I asked for a little more time, but it was removed a few days ago.

A few more details at https://github.com/richarddmorey/BayesSingleSub/issues/1

**Comment by egarpor** [comment]
Would be great to have the package soon back at CRAN.

**Comment by wibeasley** [comment]
replaced by #26
